//{{NO_DEPENDENCIES}}
// Von Microsoft Visual C++ generierte Includedatei.
// Verwendet durch gui_win_resources.rc
//
#define IDD_MAINDLG                     100
#define IDD_RX_DEV                      110
#define IDD_RX_FREQ                     120
#define IDD_RX_PROT                     130
#define IDD_RX_OUTPUT                   140
#define IDD_RX_EXPERT                   150
#define IDD_RX_SIGGRAB                  160
#define IDD_RX_STRGRAB                  170
#define IDD_RX_FLEX                     180
#define IDD_TX_DEV                      200
#define IDD_TX_FREQ                     210
#define IDD_TX_EXPERT                   220
#define IDD_TX_WARN                     230
#define IDD_TEXTREADER                  300
#define IDR_MENU1                       501
#define IDI_ICON1                       502
#define IDR_POPUPMENUS                  503
#define IDC_MAIN_RX_SDR_DSP             1001
#define IDC_MAIN_RX_SDR_BTN             1002
#define IDC_MAIN_RX_FREQ_LBL            1003
#define IDC_MAIN_RX_FREQ_DSP            1004
#define IDC_MAIN_RX_FREQ_BTN            1005
#define IDC_MAIN_RX_STARTSTOP           1006
#define IDC_MAIN_RX_COUNTER             1007
#define IDC_MAIN_RX_CHKUNK              1008
#define IDC_MAIN_RX_LIST                1009
#define IDC_MAIN_RX_DETLIST             1010
#define IDC_MAIN_RX_SCOPE               1011
#define IDC_MAIN_RX_SCOPE_LBLZ          1012
#define IDC_MAIN_RX_SCOPE_LBLP          1013
#define IDC_MAIN_RX_SCOPE_ZOOM          1014
#define IDC_MAIN_RX_SCOPE_OFFSET        1015
#define IDC_MAIN_RX_STAT01              1016
#define IDC_MAIN_RX_STAT02              1017
#define IDC_MAIN_RX_STAT03              1018
#define IDC_MAIN_TX_MODE                1019
#define IDC_MAIN_TX_FILE_DSP            1020
#define IDC_MAIN_TX_FILE_BTN            1021
#define IDC_MAIN_TX_SDR_DSP             1022
#define IDC_MAIN_TX_SDR_BTN             1023
#define IDC_MAIN_TX_FREQ_LBL            1024
#define IDC_MAIN_TX_FREQ_BTN            1025
#define IDC_MAIN_TX_FREQ_CMB            1026
#define IDC_MAIN_TX_STARTSTOP           1027
#define IDC_MAIN_TX_AUTOSTART           1028
#define IDC_MAIN_TX_COUNTER_Q           1029
#define IDC_MAIN_TX_COUNTER_S           1030
#define IDC_MAIN_TX_LIST                1031
#define IDC_MAIN_TX_DETAILS             1032
#define IDC_MAIN_TX_STAT01              1033
#define IDC_MAIN_TX_STAT02              1034
#define IDC_MAIN_TX_STAT03              1035
#define IDC_MAIN_LOG                    1036
#define IDC_RX_DEV_LIST                 1101
#define IDC_RX_DEV_REFRESH              1102
#define IDC_RX_DEV_SRATE                1103
#define IDC_RX_DEV_RAD_GAINAUTO         1104
#define IDC_RX_DEV_RAD_GAINMAN          1105
#define IDC_RX_DEV_GAIN_DSP             1106
#define IDC_RX_DEV_GAIN_SLIDER          1107
#define IDC_RX_DEV_PPM_EDT              1108
#define IDC_RX_DEV_OK                   1109
#define IDC_RX_DEV_CANCEL               1110
#define IDC_RX_FREQ_CAPTION             1201
#define IDC_RX_FREQ_LIST                1202
#define IDC_RX_FREQ_ADD                 1203
#define IDC_RX_FREQ_EDIT                1204
#define IDC_RX_FREQ_CLEAR               1205
#define IDC_RX_FREQ_HOPCAP              1206
#define IDC_RX_FREQ_HOPEDT              1207
#define IDC_RX_FREQ_HOPBTN              1208
#define IDC_RX_FREQ_OK                  1209
#define IDC_RX_FREQ_CANCEL              1211
#define IDC_RX_PROT_CAPTION             1301
#define IDC_RX_PROT_SELALL              1302
#define IDC_RX_PROT_SELNONE             1303
#define IDC_RX_PROT_DEFAULTS            1304
#define IDC_RX_PROT_LIST                1305
#define IDC_RX_PROT_OK                  1306
#define IDC_RX_PROT_CANCEL              1307
#define IDC_RX_OUT_CHK_KV               1401
#define IDC_RX_OUT_PATH_KV              1402
#define IDC_RX_OUT_BTN_KV               1403
#define IDC_RX_OUT_STDO_KV              1404
#define IDC_RX_OUT_OVR_KV               1405
#define IDC_RX_OUT_CHK_CSV              1406
#define IDC_RX_OUT_PATH_CSV             1407
#define IDC_RX_OUT_BTN_CSV              1408
#define IDC_RX_OUT_STDO_CSV             1409
#define IDC_RX_OUT_OVR_CSV              1410
#define IDC_RX_OUT_CHK_JSON             1411
#define IDC_RX_OUT_PATH_JSON            1412
#define IDC_RX_OUT_BTN_JSON             1413
#define IDC_RX_OUT_STDO_JSON            1414
#define IDC_RX_OUT_OVR_JSON             1415
#define IDC_RX_OUT_CHK_UDP              1416
#define IDC_RX_OUT_UDP_HOST             1417
#define IDC_RX_OUT_UDP_PORT             1418
#define IDC_RX_OUT_BTN_OK               1419
#define IDC_RX_OUT_BTN_CANCEL           1420
#define IDC_RX_EXP_DUR                  1501
#define IDC_RX_EXP_DUR_EDT              1502
#define IDC_RX_EXP_BYTEAMT              1503
#define IDC_RX_EXP_BYTEAMT_EDT          1504
#define IDC_RX_EXP_AUTOSTOP             1505
#define IDC_RX_EXP_CONVMD               1506
#define IDC_RX_EXP_DBGLVL               1507
#define IDC_RX_EXP_BSIZE_EDT            1510
#define IDC_RX_EXP_BSIZE_DSP            1511
#define IDC_RX_EXP_BLEV_OVR             1512
#define IDC_RX_EXP_BLEV_EDT             1513
#define IDC_RX_EXP_SVAL_OVR             1514
#define IDC_RX_EXP_SVAL_EDT             1515
#define IDC_RX_EXP_LVAL_OVR             1516
#define IDC_RX_EXP_LVAL_EDT             1517
#define IDC_RX_EXP_BTN_OK               1518
#define IDC_RX_EXP_BTN_CANCEL           1519
#define IDC_RX_SIGGRAB_CHK              1601
#define IDC_RX_SIGGRAB_PATH_LBL         1602
#define IDC_RX_SIGGRAB_PATH             1603
#define IDC_RX_SIGGRAB_PATH_BWS         1604
#define IDC_RX_SIGGRAB_PATH_CLEAR       1605
#define IDC_RX_SIGGRAB_OVR              1606
#define IDC_RX_SIGGRAB_OK               1607
#define IDC_RX_SIGGRAB_CANCEL           1608
#define IDC_RX_STRGRAB_CHK              1701
#define IDC_RX_STRGRAB_FILE_LBL         1702
#define IDC_RX_STRGRAB_FILE             1703
#define IDC_RX_STRGRAB_FILE_BWS         1704
#define IDC_RX_STRGRAB_STDOUT           1705
#define IDC_RX_STRGRAB_OVR              1706
#define IDC_RX_STRGRAB_OK               1707
#define IDC_RX_STRGRAB_CANCEL           1708
#define IDC_RX_FLEX_CAPTION             1801
#define IDC_RX_FLEX_ADD                 1802
#define IDC_RX_FLEX_CLEAR               1803
#define IDC_RX_FLEX_LIST                1804
#define IDC_RX_FLEX_OK                  1805
#define IDC_RX_FLEX_CANCEL              1806
#define IDC_TX_DEV_LIST                 2001
#define IDC_TX_DEV_REFRESH              2002
#define IDC_TX_DEV_OK                   2003
#define IDC_TX_DEV_CANCEL               2004
#define IDC_TX_FREQ_SAMPRATE            2101
#define IDC_TX_FREQ_SRATEDSP            2102
#define IDC_TX_FREQ_WARNING             2103
#define IDC_TX_FREQ_RADAUTO             2104
#define IDC_TX_FREQ_SRATE_SL            2105
#define IDC_TX_FREQ_RADMAN              2106
#define IDC_TX_FREQ_MULT_DSP            2107
#define IDC_TX_FREQ_MULT_SL             2108
#define IDC_TX_FREQ_DIV_DSP             2109
#define IDC_TX_FREQ_DIV_SL              2110
#define IDC_TX_FREQ_FRAC_DSP            2111
#define IDC_TX_FREQ_FRAC_SL             2112
#define IDC_TX_FREQ_CARR1_DSP           2113
#define IDC_TX_FREQ_CARR1_SL            2114
#define IDC_TX_FREQ_CARR1_STAT          2115
#define IDC_TX_FREQ_CARR2_DSP           2116
#define IDC_TX_FREQ_CARR2_SL            2117
#define IDC_TX_FREQ_CARR2_STAT          2118
#define IDC_TX_FREQ_HARM                2119
#define IDC_TX_FREQ_OK                  2120
#define IDC_TX_FREQ_CANCEL              2121
#define IDC_TX_EXP_DBGLVL_EDT           2201
#define IDC_TX_EXP_INITIME_EDT          2202
#define IDC_TX_EXP_BTN_OK               2203
#define IDC_TX_EXP_BTN_CANCEL           2204
#define IDC_TX_WARN_TXT                 2301
#define IDC_TX_WARN_CHK                 2302
#define IDC_TX_WARN_OK                  2303
#define IDC_TEXTREADER_EDIT             3001
#define IDC_TEXTREADER_OK               3002
#define IDC_TEXTREADER_CANCEL           3003
#define ID_RX_FILE                      9001
#define ID_RX_FILE_HIST0                9002
#define ID_RX_FILE_HIST1                9003
#define ID_RX_FILE_HIST2                9004
#define ID_RX_FILE_HIST3                9005
#define ID_RX_FILE_HIST4                9006
#define ID_RX_FILE_HIST5                9007
#define ID_RX_FILE_HIST6                9008
#define ID_RX_FILE_HIST7                9009
#define ID_RX_FILE_HIST8                9010
#define ID_RX_FILE_HIST9                9011
#define ID_PROG_CLOSE                   9012
#define ID_RX_PROT                      9020
#define ID_RX_FLEXPROT                  9021
#define ID_RX_MODE_ANALYZE              9022
#define ID_RX_MODE_PLSANLZ              9023
#define ID_RX_DUMP_STREAM               9024
#define ID_RX_DUMP_SIGS                 9025
#define ID_RX_DSP_UNKNOWN               9026
#define ID_RX_DSP_HIRES                 9027
#define ID_RX_DSP_META                  9028
#define ID_RX_DSP_BITS                  9029
#define ID_RX_OUT                       9030
#define ID_RX_EXP                       9031
#define ID_TX_DEV                       9040
#define ID_TX_FREQ                      9041
#define ID_TX_EXP                       9042
#define ID_RXLIST_ADDTOTXQUEUE          9049
#define ID_HELP_ABOUT                   9050
#define ID_RXLIST_SIGTX                 9060
#define ID_RXLIST_PLSTX                 9061
#define ID_RXLIST_SAVESIG               9062
#define ID_RXLIST_SAVEPLS               9063
#define ID_RXLIST_DEL                   9064
#define ID_RXLIST_DELALL                9065
#define ID_RDLIST_COPY                  9066
#define ID_RDLIST_COPYALL               9067
#define ID_RDLIST_SAVEALL               9068
#define ID_FRQLIST_DELSEL               9070
#define ID_FRQLIST_DELALL               9071
#define ID_FLXLIST_EDIT                 9080
#define ID_FLXLIST_DELSEL               9081
#define ID_FLXLIST_DELALL               9082
#define ID_PRTLIST_TOGGLE               9090
#define ID_PRTLIST_ENABLE               9091
#define ID_PRTLIST_DISABLE              9092
#define ID_TXLIST_RESEND                9100
#define ID_TXLIST_DEL                   9101
#define ID_TXLIST_DELALL                9102
#define ID_LOG_COPY                     9110
#define ID_LOG_SAVE                     9111
#define ID_LOG_CLEAR                    9112
#define ID_PROTLIST_EDITPARAMETER       9120
#define ID_PROTLIST_PAREDT              9121
#define ID_PRTLIST_PAREDT               9122
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        204
#define _APS_NEXT_COMMAND_VALUE         9050
#define _APS_NEXT_CONTROL_VALUE         2021
#define _APS_NEXT_SYMED_VALUE           504
#endif
#endif
